name: ci
on: [push, pull_request]
jobs:
  moonbit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbitlang/setup-moonbit@v1
      - run: moon fmt --check
      - run: moon info
      - run: moon check --target all --deny-warn
      - run: moon test --target all --deny-warn
      - run: moon build --target wasm,wasm-gc,js,native
